Load CSV and preview

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\PRATHAMESH\Downloads\pokemon.csv")

Check shape

In [2]:
df.shape

(1045, 23)


Column names list

In [3]:
df.columns.tolist()

['Unnamed: 0',
 'Name',
 'Evolution',
 'Type',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp.Atk',
 'Sp.Def',
 'Speed',
 'Species',
 'Height',
 'Weight',
 'abilities',
 'ev_yield',
 'catch_rate',
 'base_friendship',
 'base_experience',
 'growth_rate',
 'eggs_groups',
 'gender_rate',
 'eggs_cycles_rate']

Data types of all columns

In [4]:
df.dtypes

Unnamed: 0          int64
Name                  str
Evolution             str
Type                  str
Total               int64
HP                  int64
Attack              int64
Defense             int64
Sp.Atk              int64
Sp.Def              int64
Speed               int64
Species               str
Height                str
Weight                str
abilities             str
ev_yield              str
catch_rate            str
base_friendship       str
base_experience     int64
growth_rate           str
eggs_groups           str
gender_rate           str
eggs_cycles_rate      str
dtype: object

Dataset summary

In [5]:
df.describe()

,Unnamed: 0,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,base_experience
count,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000,1045.000000
mean,522.000000,439.314833,70.067943,80.466986,74.661244,73.022010,72.288995,68.807656,152.729187
std,301.809819,121.970701,26.671411,32.413665,31.237903,32.724797,28.074148,30.210094,77.323984
min,0.000000,175.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,36.000000
25%,261.000000,330.000000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,67.000000
50%,522.000000,458.000000,68.000000,77.000000,70.000000,65.000000,70.000000,65.000000,159.000000
75%,783.000000,515.000000,82.000000,100.000000,90.000000,95.000000,90.000000,90.000000,185.000000
max,1044.000000,1125.000000,255.000000,190.000000,250.000000,194.000000,250.000000,200.000000,608.000000

Count nulls per column

In [6]:
df.isnull().sum()

Unnamed: 0          0
Name                0
Evolution           0
Type                0
Total               0
HP                  0
Attack              0
Defense             0
Sp.Atk              0
Sp.Def              0
Speed               0
Species             0
Height              0
Weight              0
abilities           0
ev_yield            0
catch_rate          0
base_friendship     0
base_experience     0
growth_rate         0
eggs_groups         0
gender_rate         0
eggs_cycles_rate    0
dtype: int64

Unique values in a column ('Total')

In [7]:
df['Total'].nunique()

216

Value counts

In [8]:
df['Name'].value_counts()

Name
Rotom         6
Castform      4
Deoxys        4
Darmanitan    4
Pumpkaboo     4
             ..
Zarude        1
Regieleki     1
Regidrago     1
Glastrier     1
Spectrier     1
Name: count, Length: 898, dtype: int64


Info summary

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1045 entries, 0 to 1044
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1045 non-null   int64
 1   Name              1045 non-null   str
 2   Evolution         1045 non-null   str
 3   Type              1045 non-null   str
 4   Total             1045 non-null   int64
 5   HP                1045 non-null   int64
 6   Attack            1045 non-null   int64
 7   Defense           1045 non-null   int64
 8   Sp.Atk            1045 non-null   int64
 9   Sp.Def            1045 non-null   int64
 10  Speed             1045 non-null   int64
 11  Species           1045 non-null   str
 12  Height            1045 non-null   str
 13  Weight            1045 non-null   str
 14  abilities         1045 non-null   str
 15  ev_yield          1045 non-null   str
 16  catch_rate        1045 non-null   str
 17  base_friendship   1045 non-null   str
 18  base_experience   1045 non-null   int64
 19  growth_rate       1045 non-null   str
 20  eggs_groups       1045 non-null   str
 21  gender_rate       1045 non-null   str
 22  eggs_cycles_rate  1045 non-null   str
dtypes: int64(9), str(14)
memory usage: 187.9 KB

Sample random rows

In [10]:
df.sample(2,random_state=150)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
714,714,Axew,,Dragon,320,46,87,60,30,40,...,18.0 kg (39.7 lbs),1. Rivalry2. Mold BreakerUnnerve (hidden ability),1 Attack,"75 (9.8% with PokéBall, full HP)",35 (lower than normal),64,Slow,"Dragon, Monster","50% male, 50% female","40 (10,024–10,280 steps)"
706,706,Tynamo,,Electric,275,35,55,40,45,40,...,0.3 kg (0.7 lbs),1. Levitate,1 Speed,"190 (24.8% with PokéBall, full HP)",50 (normal),55,Slow,Amorphous,"50% male, 50% female","20 (4,884–5,140 steps)"

Filter by single condition

In [11]:
df[df["Total"] > 500].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,100.0 kg (220.5 lbs),1. OvergrowChlorophyll (hidden ability),"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,100.0 kg (220.5 lbs),1. OvergrowChlorophyll (hidden ability),"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"

Filter with multiple conditions

In [12]:
df[(df['HP']> 150)&(df['Total']> 800)]

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,950.0 kg (2094.4 lbs),1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"

Filter by list of values

In [13]:
total = [500,120]
df[df['Total'].isin(total)].head(2)  
# returns only that rows where "Total" = 500/120

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
73,73,Golduck,,Water,500,80,82,78,95,80,...,76.6 kg (168.9 lbs),1. Damp2. Cloud NineSwift Swim (hidden ability),2 Special Attack,"75 (9.8% with PokéBall, full HP)",50 (normal),175,Medium Fast,"Field, Water 1","50% male, 50% female","20 (4,884–5,140 steps)"
83,83,Alakazam,,Psychic,500,55,50,45,135,95,...,48.0 kg (105.8 lbs),1. Synchronize2. Inner FocusMagic Guard (hidde...,3 Special Attack,"50 (6.5% with PokéBall, full HP)",50 (normal),225,Medium Slow,Human-Like,"75% male, 25% female","20 (4,884–5,140 steps)"

Filter rows with missing values

In [14]:
df[df['Total'].isnull()]

# df['Total'].notna()  # notnull

Empty DataFrame
Columns: [Unnamed: 0, Name, Evolution, Type, Total, HP, Attack, Defense, Sp.Atk, Sp.Def, Speed, Species, Height, Weight, abilities, ev_yield, catch_rate, base_friendship, base_experience, growth_rate, eggs_groups, gender_rate, eggs_cycles_rate]
Index: []

[0 rows x 23 columns]

Filter string column

In [15]:
df['Name'].str.contains('Pikachu',case=False, na= False)

0       False
1       False
2       False
3       False
4       False
        ...
1040    False
1041    False
1042    False
1043    False
1044    False
Name: Name, Length: 1045, dtype: bool

Select specific columns

In [16]:
df[['Name','Total']].head(2)

        Name  Total
0  Bulbasaur    318
1    Ivysaur    405

Filter by date range

In [17]:
df['Date'] = pd.to_datetime(df['Total'])
df[(df['Date'] >= '1970-01-01')].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1. OvergrowChlorophyll (hidden ability),1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,1. OvergrowChlorophyll (hidden ability),"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405

Select rows 0–2 and columns 'name', 'price' using loc.

In [18]:
df.loc[0:2 , ['Name','Total']]

        Name  Total
0  Bulbasaur    318
1    Ivysaur    405
2   Venusaur    525

Select first 2 rows and first 3 columns by position

In [19]:
df.iloc[0:2, 0: 3]

   Unnamed: 0       Name Evolution
0           0  Bulbasaur
1           1    Ivysaur


Query method
Filter rows using a SQL-like string expression.

In [20]:
df.query('Total > 500 & HP >= 100').head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
150,150,Kangaskhan,Mega Kangaskhan,Normal,590,105,125,100,60,100,...,1. Early Bird2. ScrappyInner Focus (hidden abi...,2 HP,"45 (5.9% with PokéBall, full HP)",50 (normal),172,Medium Fast,Monster,"0% male, 100% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000590
169,169,Lapras,,Water Ice,535,130,85,80,85,95,...,1. Water Absorb2. Shell ArmorHydration (hidden...,2 HP,"45 (5.9% with PokéBall, full HP)",50 (normal),187,Slow,"Monster, Water 1","50% male, 50% female","40 (10,024–10,280 steps)",1970-01-01 00:00:00.000000535

Sort by one column

In [21]:
df.sort_values('HP', ascending= False).head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000001125
294,294,Blissey,,Normal,540,255,10,10,75,135,...,1. Natural Cure2. Serene GraceHealer (hidden a...,3 HP,"30 (3.9% with PokéBall, full HP)",140 (higher than normal),608,Fast,Fairy,"0% male, 100% female","40 (10,024–10,280 steps)",1970-01-01 00:00:00.000000540


Sort by multiple columns

In [22]:
df.sort_values(['Total','HP'], ascending=False)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000001125
194,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
195,195,Mewtwo,Mega Mewtwo Y,Psychic,780,106,150,70,194,120,...,1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
464,464,Rayquaza,Mega Rayquaza,Dragon Flying,780,105,180,100,180,100,...,1. Air Lock,"2 Attack, 1 Special Attack","45 (5.9% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
460,460,Kyogre,Primal Kyogre,Water,770,100,150,90,180,160,...,1. Drizzle,3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),302,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,357,Azurill,,Normal Fairy,190,50,20,40,20,40,...,1. Thick Fat2. Huge PowerSap Sipper (hidden ab...,1 HP,"150 (19.6% with PokéBall, full HP)",50 (normal),38,Fast,Undiscovered,"25% male, 75% female","10 (2,314–2,570 steps)",1970-01-01 00:00:00.000000190
1009,1009,Snom,,Ice Bug,185,30,25,35,45,30,...,1. Shield DustIce Scales (hidden ability),1 Special Attack,"190 (24.8% with PokéBall, full HP)",50 (normal),37,Medium Fast,Bug,"50% male, 50% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000185
237,237,Sunkern,,Grass,180,30,30,30,30,30,...,1. Chlorophyll2. Solar PowerEarly Bird (hidden...,1 Special Attack,"235 (30.7% with PokéBall, full HP)",50 (normal),36,Medium Slow,Grass,"50% male, 50% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000180
960,960,Blipbug,,Bug,180,25,20,20,25,45,...,1. Swarm2. Compound EyesTelepathy (hidden abil...,1 Special Defense,"255 (33.3% with PokéBall, full HP)",50 (normal),36,Medium Fast,Bug,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000180
877,877,Wishiwashi,Solo Form,Water,175,45,20,20,25,25,...,1. Schooling,1 HP,"60 (7.8% with PokéBall, full HP)",50 (normal),61,Fast,Water 2,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000175


Sort and reset index

In [23]:
df.sort_values(["Total","HP"], ascending= False).reset_index(drop=True)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
0,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000001125
1,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
2,195,Mewtwo,Mega Mewtwo Y,Psychic,780,106,150,70,194,120,...,1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
3,464,Rayquaza,Mega Rayquaza,Dragon Flying,780,105,180,100,180,100,...,1. Air Lock,"2 Attack, 1 Special Attack","45 (5.9% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780
4,460,Kyogre,Primal Kyogre,Water,770,100,150,90,180,160,...,1. Drizzle,3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),302,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,357,Azurill,,Normal Fairy,190,50,20,40,20,40,...,1. Thick Fat2. Huge PowerSap Sipper (hidden ab...,1 HP,"150 (19.6% with PokéBall, full HP)",50 (normal),38,Fast,Undiscovered,"25% male, 75% female","10 (2,314–2,570 steps)",1970-01-01 00:00:00.000000190
1041,1009,Snom,,Ice Bug,185,30,25,35,45,30,...,1. Shield DustIce Scales (hidden ability),1 Special Attack,"190 (24.8% with PokéBall, full HP)",50 (normal),37,Medium Fast,Bug,"50% male, 50% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000185
1042,237,Sunkern,,Grass,180,30,30,30,30,30,...,1. Chlorophyll2. Solar PowerEarly Bird (hidden...,1 Special Attack,"235 (30.7% with PokéBall, full HP)",50 (normal),36,Medium Slow,Grass,"50% male, 50% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000180
1043,960,Blipbug,,Bug,180,25,20,20,25,45,...,1. Swarm2. Compound EyesTelepathy (hidden abil...,1 Special Defense,"255 (33.3% with PokéBall, full HP)",50 (normal),36,Medium Fast,Bug,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000180
1044,877,Wishiwashi,Solo Form,Water,175,45,20,20,25,25,...,1. Schooling,1 HP,"60 (7.8% with PokéBall, full HP)",50 (normal),61,Fast,Water 2,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000175

Rank rows
Add a new column that ranks rows by 'sales' (1 = highest).

In [24]:
df['Name'].rank(ascending=False , method= 'dense').astype(int)

0       816
1       527
2        63
3        63
4       791
       ...
1040    606
1041    167
1042    808
1043    808
1044    808
Name: Name, Length: 1045, dtype: int64

Top N rows by ....

In [25]:
df.nlargest(2,'Total')

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000001125
194,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000780

Column-level aggregations

In [26]:

print(df['Total'].mean())
print(df['Total'].median())
print(df['Total'].std())

439.31483253588516
458.0
121.97070113333595

agg() with multiple functions

In [27]:
df[['HP','Total']].agg(['mean','min','max','sum'])

                HP          Total
mean     70.067943     439.314833
min       1.000000     175.000000
max     255.000000    1125.000000
sum   73221.000000  459084.000000

Custom aggregation

In [28]:
df['HP'].agg(lambda x: x.max() - x.min())
# # or
# def HP_range(x):
#     return x.max() - x.min()
# df["HP"].agg(HP_range)

np.int64(254)

Crosstab
Count combinations of two categorical columns.

In [29]:
pd.crosstab(df['Type'], df['Name'])

Name,Abomasnow,Abra,Absol,Accelgor,Aegislash,Aerodactyl,Aggron,Aipom,Alakazam,Alcremie,...,Zarude,Zebstrika,Zekrom,Zeraora,Zigzagoon,Zoroark,Zorua,Zubat,Zweilous,Zygarde
Type,,,,,,,,,,,,,,,,,,,,,
Bug,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bug Electric,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bug Fairy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bug Fighting,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Bug Fire,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Water Ice,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water Poison,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water Psychic,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water Rock,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water Steel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Cumulative sum

In [30]:
df['Total_cumsum'] = df['Total'].cumsum()
df

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318,318
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405,723
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000525,1248
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873
4,4,Charmander,,Fire,309,39,52,43,60,50,...,1 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000309,2182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,Glastrier,,Ice,580,100,145,130,65,110,...,3 Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,456644
1041,1041,Spectrier,,Ghost,580,100,65,60,145,80,...,3 Special Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,457224
1042,1042,Calyrex,,Psychic Grass,500,100,80,80,80,80,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000500,457724
1043,1043,Calyrex,Ice Rider,Psychic Ice,680,100,165,150,85,130,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,458404
1044,1044,Calyrex,Shadow Rider,Psychic Ghost,680,100,85,80,165,100,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,459084

Rolling average

In [31]:
df['HP'].rolling(window=7).mean()

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
           ...
1040    106.428571
1041    112.142857
1042    112.142857
1043    112.142857
1044    111.428571
Name: HP, Length: 1045, dtype: float64

Basic groupby

In [32]:
df.groupby('HP')['Total'].mean()

HP
1      236.000000
10     265.000000
20     285.833333
25     261.250000
28     234.000000
          ...
200    580.000000
216    708.000000
223    570.000000
250    450.000000
255    832.500000
Name: Total, Length: 103, dtype: float64

Groupby with multiple columns

In [33]:
df.groupby(['HP','Total'])['Sp.Atk'].sum().reset_index()

      HP  Total  Sp.Atk
0      1    236      30
1     10    265      70
2     20    200      25
3     20    205      35
4     20    295      30
..   ...    ...     ...
711  216    708      91
712  223    570      97
713  250    450      35
714  255    540      75
715  255   1125     125

[716 rows x 3 columns]

Groupby agg — multiple stats

In [34]:
df.groupby('HP').agg(
    total_hp = ('HP','sum'),
    avg_hp = ('HP','mean')
)

     total_hp  avg_hp
HP
1           1     1.0
10         20    10.0
20        120    20.0
25        100    25.0
28         56    28.0
..        ...     ...
200       200   200.0
216       216   216.0
223       223   223.0
250       250   250.0
255       510   255.0

[103 rows x 2 columns]


Filter groups by size

In [35]:
df.groupby('Total').filter(lambda x: len(x) == 2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873
7,7,Charizard,Mega Charizard X,Fire Dragon,634,78,130,111,130,85,...,3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000634,3755
8,8,Charizard,Mega Charizard Y,Fire Flying,634,78,104,78,159,115,...,3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000634,4389
22,22,Pidgeot,,Normal Flying,479,83,80,75,70,70,...,3 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),216,Medium Slow,Flying,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000479,9432
28,28,Spearow,,Normal Flying,262,40,60,30,31,31,...,1 Speed,"255 (33.3% with PokéBall, full HP)",50 (normal),52,Medium Fast,Flying,"50% male, 50% female","15 (3,599–3,855 steps)",1970-01-01 00:00:00.000000262,11605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,986,Toxtricity,Amped Form,Electric Poison,502,75,98,70,114,70,...,2 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),176,Medium Slow,Human-Like,"50% male, 50% female","25 (6,169–6,425 steps)",1970-01-01 00:00:00.000000502,430291
992,992,Polteageist,,Ghost,508,60,65,65,134,114,...,2 Special Attack,"60 (7.8% with PokéBall, full HP)",50 (normal),178,Medium Fast,"Amorphous, Mineral",Genderless,"20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000508,432727
1002,1002,Sirfetch'd,,Fighting,507,62,135,95,68,82,...,2 Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),177,Medium Fast,"Field, Flying","50% male, 50% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000507,436994
1016,1016,Morpeko,Full Belly Mode,Electric Dark,436,58,95,58,70,58,...,2 Speed,"180 (23.5% with PokéBall, full HP)",50 (normal),153,Medium Fast,"Fairy, Field","50% male, 50% female","10 (2,314–2,570 steps)",1970-01-01 00:00:00.000000436,443123
1017,1017,Morpeko,Hangry Mode,Electric Dark,436,58,95,58,70,58,...,2 Speed,"180 (23.5% with PokéBall, full HP)",50 (normal),153,Medium Fast,"Fairy, Field","50% male, 50% female","10 (2,314–2,570 steps)",1970-01-01 00:00:00.000000436,443559


Transform — group mean fill

In [36]:
df.groupby('Total')['HP'].transform(
    lambda x: x.fillna(x.mean())
)

0        45
1        60
2        80
3        80
4        39
       ...
1040    100
1041    100
1042    100
1043    100
1044    100
Name: HP, Length: 1045, dtype: int64

Drop duplicate rows

In [37]:
df.drop_duplicates()

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318,318
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405,723
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000525,1248
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873
4,4,Charmander,,Fire,309,39,52,43,60,50,...,1 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000309,2182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,Glastrier,,Ice,580,100,145,130,65,110,...,3 Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,456644
1041,1041,Spectrier,,Ghost,580,100,65,60,145,80,...,3 Special Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,457224
1042,1042,Calyrex,,Psychic Grass,500,100,80,80,80,80,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000500,457724
1043,1043,Calyrex,Ice Rider,Psychic Ice,680,100,165,150,85,130,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,458404
1044,1044,Calyrex,Shadow Rider,Psychic Ghost,680,100,85,80,165,100,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,459084


Fill missing values

In [38]:
df['Sp.Atk'].fillna(df['Attack'].median(), inplace= True)

C:\Users\PRATHAMESH\AppData\Local\Temp\ipykernel_22140\3710493673.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Sp.Atk'].fillna(df['Attack'].median(), inplace= True)

0        65
1        80
2       100
3       122
4        60
       ...
1040     65
1041    145
1042     80
1043     85
1044    165
Name: Sp.Atk, Length: 1045, dtype: int64


Drop rows with nulls

In [39]:
df.dropna()

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318,318
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405,723
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000525,1248
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873
4,4,Charmander,,Fire,309,39,52,43,60,50,...,1 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000309,2182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,Glastrier,,Ice,580,100,145,130,65,110,...,3 Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,456644
1041,1041,Spectrier,,Ghost,580,100,65,60,145,80,...,3 Special Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,457224
1042,1042,Calyrex,,Psychic Grass,500,100,80,80,80,80,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000500,457724
1043,1043,Calyrex,Ice Rider,Psychic Ice,680,100,165,150,85,130,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,458404
1044,1044,Calyrex,Shadow Rider,Psychic Ghost,680,100,85,80,165,100,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,459084

Rename columns

In [40]:
df.columns.str.lower().str.replace(' ', '_')

Index(['unnamed:_0', 'name', 'evolution', 'type', 'total', 'hp', 'attack',
       'defense', 'sp.atk', 'sp.def', 'speed', 'species', 'height', 'weight',
       'abilities', 'ev_yield', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'eggs_groups', 'gender_rate',
       'eggs_cycles_rate', 'date', 'total_cumsum'],
      dtype='str')


Change data type

In [41]:
pd.to_numeric(df['Height'], errors='coerce')

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1040   NaN
1041   NaN
1042   NaN
1043   NaN
1044   NaN
Name: Height, Length: 1045, dtype: float64

Strip whitespace from strings

In [42]:
str_cols = df.select_dtypes(include='object').columns
df[str_cols] = df[str_cols].apply(lambda x: x.str.strip())

C:\Users\PRATHAMESH\AppData\Local\Temp\ipykernel_22140\3956375958.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include='object').columns

In [43]:
df.replace('Name', np.nan, inplace= True)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318,318
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405,723
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000525,1248
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873
4,4,Charmander,,Fire,309,39,52,43,60,50,...,1 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000309,2182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,Glastrier,,Ice,580,100,145,130,65,110,...,3 Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,456644
1041,1041,Spectrier,,Ghost,580,100,65,60,145,80,...,3 Special Attack,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,457224
1042,1042,Calyrex,,Psychic Grass,500,100,80,80,80,80,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000500,457724
1043,1043,Calyrex,Ice Rider,Psychic Ice,680,100,165,150,85,130,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,458404
1044,1044,Calyrex,Shadow Rider,Psychic Ghost,680,100,85,80,165,100,...,3 HP,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,459084

Create bins from continuous data

In [44]:
pd.cut(
    df['Sp.Atk'],
    bins=[10,50,100,200],
    labels=['low','avg','good']
)

0        avg
1        avg
2        avg
3       good
4        avg
        ...
1040     avg
1041    good
1042     avg
1043     avg
1044    good
Name: Sp.Atk, Length: 1045, dtype: category
Categories (3, str): ['low' < 'avg' < 'good']

In [45]:
pd.cut(
    df['Total'],
    bins= [0,50,100,500,1000,1500],
    labels=['Worst','low','good','better','strong']
)

0         good
1         good
2       better
3       better
4         good
         ...
1040    better
1041    better
1042      good
1043    better
1044    better
Name: Total, Length: 1045, dtype: category
Categories (5, str): ['Worst' < 'low' < 'good' < 'better' < 'strong']


Merge two DataFrames (inner join)

In [46]:
df1 = pd.read_csv(r"C:\Users\PRATHAMESH\Downloads\government-finance-statistics-central-government-year-ended-june-2025.CSV")
merged =pd.merge(df , df1, left_on='Name',right_on="Series_reference", how='inner')
print(merged)

Empty DataFrame
Columns: [Unnamed: 0, Name, Evolution, Type, Total, HP, Attack, Defense, Sp.Atk, Sp.Def, Speed, Species, Height, Weight, abilities, ev_yield, catch_rate, base_friendship, base_experience, growth_rate, eggs_groups, gender_rate, eggs_cycles_rate, Date, Total_cumsum, Series_reference, Period, Data_value, STATUS, Group, Subject, Series_title_1, Series_title_2, Series_title_3, Series_title_4, Series_title_5, UNITS, MAGNTUDE]
Index: []

[0 rows x 38 columns]

In [47]:
df_combined = pd.concat([df1, df], ignore_index=True)
print(df_combined)

      Series_reference   Period  Data_value   STATUS  \
0     GFSA.SCS01G01Z90  2009.06      3400.0  REVISED
1     GFSA.SCS01G01Z90  2010.06     -3893.0  REVISED
2     GFSA.SCS01G01Z90  2011.06    -13109.0  REVISED
3     GFSA.SCS01G01Z90  2012.06     -3908.0  REVISED
4     GFSA.SCS01G01Z90  2013.06     -1018.0  REVISED
...                ...      ...         ...      ...
3887               NaN      NaN         NaN      NaN
3888               NaN      NaN         NaN      NaN
3889               NaN      NaN         NaN      NaN
3890               NaN      NaN         NaN      NaN
3891               NaN      NaN         NaN      NaN

                                                  Group  \
0     Central Government, Operating Statement, Net B...
1     Central Government, Operating Statement, Net B...
2     Central Government, Operating Statement, Net B...
3     Central Government, Operating Statement, Net B...
4     Central Government, Operating Statement, Net B...
...                                                 ...
3887                                                NaN
3888                                                NaN
3889                                                NaN
3890                                                NaN
3891                                                NaN

                                    Subject         Series_title_1  \
0     Government Financial Statistics - GFS  Net operating balance
1     Government Financial Statistics - GFS  Net operating balance
2     Government Financial Statistics - GFS  Net operating balance
3     Government Financial Statistics - GFS  Net operating balance
4     Government Financial Statistics - GFS  Net operating balance
...                                     ...                    ...
3887                                    NaN                    NaN
3888                                    NaN                    NaN
3889                                    NaN                    NaN
3890                                    NaN                    NaN
3891                                    NaN                    NaN

     Series_title_2 Series_title_3 Series_title_4  ...          ev_yield  \
0               NaN            NaN            NaN  ...               NaN
1               NaN            NaN            NaN  ...               NaN
2               NaN            NaN            NaN  ...               NaN
3               NaN            NaN            NaN  ...               NaN
4               NaN            NaN            NaN  ...               NaN
...             ...            ...            ...  ...               ...
3887            NaN            NaN            NaN  ...          3 Attack
3888            NaN            NaN            NaN  ...  3 Special Attack
3889            NaN            NaN            NaN  ...              3 HP
3890            NaN            NaN            NaN  ...              3 HP
3891            NaN            NaN            NaN  ...              3 HP

                           catch_rate           base_friendship  \
0                                 NaN                       NaN
1                                 NaN                       NaN
2                                 NaN                       NaN
3                                 NaN                       NaN
4                                 NaN                       NaN
...                               ...                       ...
3887  3 (0.4% with PokéBall, full HP)    35 (lower than normal)
3888  3 (0.4% with PokéBall, full HP)    35 (lower than normal)
3889  3 (0.4% with PokéBall, full HP)  100 (higher than normal)
3890  3 (0.4% with PokéBall, full HP)  100 (higher than normal)
3891  3 (0.4% with PokéBall, full HP)  100 (higher than normal)

      base_experience growth_rate   eggs_groups gender_rate  \
0                 NaN         NaN           NaN         NaN
1                 NaN         NaN           NaN         NaN
2                 NaN         NaN           NaN         NaN
3                 NaN         NaN           NaN         NaN
4                 NaN         NaN           NaN         NaN
...               ...         ...           ...         ...
3887            290.0        Slow  Undiscovered  Genderless
3888            290.0        Slow  Undiscovered  Genderless
3889            250.0        Slow  Undiscovered  Genderless
3890            250.0        Slow  Undiscovered  Genderless
3891            250.0        Slow  Undiscovered  Genderless

               eggs_cycles_rate                          Date  Total_cumsum
0                           NaN                           NaT           NaN
1                           NaN                           NaT           NaN
2                           NaN                           NaT           NaN
3                           NaN                           NaT           NaN
4                           NaN                           NaT           NaN
...                         ...                           ...           ...
3887  120 (30,584–30,840 steps) 1970-01-01 00:00:00.000000580      456644.0
3888  120 (30,584–30,840 steps) 1970-01-01 00:00:00.000000580      457224.0
3889  120 (30,584–30,840 steps) 1970-01-01 00:00:00.000000500      457724.0
3890  120 (30,584–30,840 steps) 1970-01-01 00:00:00.000000680      458404.0
3891  120 (30,584–30,840 steps) 1970-01-01 00:00:00.000000680      459084.0

[3892 rows x 38 columns]

Pivot table

In [48]:
df.pivot_table(
    values='Total',
    index='Sp.Atk',
    columns='Name',
    aggfunc='mean',
    fill_value=0
).round(2)

Name,Abomasnow,Abra,Absol,Accelgor,Aegislash,Aerodactyl,Aggron,Aipom,Alakazam,Alcremie,...,Zarude,Zebstrika,Zekrom,Zeraora,Zigzagoon,Zoroark,Zorua,Zubat,Zweilous,Zygarde
Sp.Atk,,,,,,,,,,,,,,,,,,,,,
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
173,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


Melt — wide to long format

In [53]:
df_long = pd.melt(
    frame=df,
    id_vars= ['Name'],
    value_vars=['Total','Sp.Atk','HP'],
    var_name= 'Stats',
    value_name='Value'
)
print(df_long)

            Name  Stats  Value
0      Bulbasaur  Total    318
1        Ivysaur  Total    405
2       Venusaur  Total    525
3       Venusaur  Total    625
4     Charmander  Total    309
...          ...    ...    ...
3130   Glastrier     HP    100
3131   Spectrier     HP    100
3132     Calyrex     HP    100
3133     Calyrex     HP    100
3134     Calyrex     HP    100

[3135 rows x 3 columns]

Apply a custom function row-wise

In [57]:
def Total_stat(Total):
    if Total < 100:
        return 'low'
    elif Total < 500:
        return 'mid'
    else:
        return 'high'

df['Total_stat'] = df['Total'].apply(Total_stat)
df

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Date,Total_cumsum,Total_stat
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000318,318,mid
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000405,723,mid
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000525,1248,high
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000625,1873,high
4,4,Charmander,,Fire,309,39,52,43,60,50,...,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",1970-01-01 00:00:00.000000309,2182,mid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,Glastrier,,Ice,580,100,145,130,65,110,...,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,456644,high
1041,1041,Spectrier,,Ghost,580,100,65,60,145,80,...,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000580,457224,high
1042,1042,Calyrex,,Psychic Grass,500,100,80,80,80,80,...,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000500,457724,high
1043,1043,Calyrex,Ice Rider,Psychic Ice,680,100,165,150,85,130,...,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,458404,high
1044,1044,Calyrex,Shadow Rider,Psychic Ghost,680,100,85,80,165,100,...,"3 (0.4% with PokéBall, full HP)",100 (higher than normal),250,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",1970-01-01 00:00:00.000000680,459084,high