In [151]:
import pandas as pd
import numpy as np 
df = pd.read_csv(r"C:\Users\PRATHAMESH\Downloads\pokemon.csv")

In [152]:
df.head(10)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,6.9 kg (15.2 lbs),1. OvergrowChlorophyll (hidden ability),1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,13.0 kg (28.7 lbs),1. OvergrowChlorophyll (hidden ability),"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,100.0 kg (220.5 lbs),1. OvergrowChlorophyll (hidden ability),"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,100.0 kg (220.5 lbs),1. OvergrowChlorophyll (hidden ability),"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
4,4,Charmander,,Fire,309,39,52,43,60,50,...,8.5 kg (18.7 lbs),1. BlazeSolar Power (hidden ability),1 Speed,"45 (5.9% with PokéBall, full HP)",50 (normal),62,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
5,5,Charmeleon,,Fire,405,58,64,58,80,65,...,19.0 kg (41.9 lbs),1. BlazeSolar Power (hidden ability),"1 Special Attack, 1 Speed","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
6,6,Charizard,,Fire Flying,534,78,84,78,109,85,...,90.5 kg (199.5 lbs),1. BlazeSolar Power (hidden ability),3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
7,7,Charizard,Mega Charizard X,Fire Dragon,634,78,130,111,130,85,...,90.5 kg (199.5 lbs),1. BlazeSolar Power (hidden ability),3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
8,8,Charizard,Mega Charizard Y,Fire Flying,634,78,104,78,159,115,...,90.5 kg (199.5 lbs),1. BlazeSolar Power (hidden ability),3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)"
9,9,Squirtle,,Water,314,44,48,65,50,64,...,9.0 kg (19.8 lbs),1. TorrentRain Dish (hidden ability),1 Defense,"45 (5.9% with PokéBall, full HP)",50 (normal),63,Medium Slow,"Monster, Water 1","87.5% male, 12.5% female","20 (4,884–5,140 steps)"

In [153]:
df[df['Total'] > 800]

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,950.0 kg (2094.4 lbs),1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"

In [154]:
df[['Name','Type','Total']]

            Name           Type  Total
0      Bulbasaur   Grass Poison    318
1        Ivysaur   Grass Poison    405
2       Venusaur   Grass Poison    525
3       Venusaur   Grass Poison    625
4     Charmander          Fire     309
...          ...            ...    ...
1040   Glastrier           Ice     580
1041   Spectrier         Ghost     580
1042     Calyrex  Psychic Grass    500
1043     Calyrex    Psychic Ice    680
1044     Calyrex  Psychic Ghost    680

[1045 rows x 3 columns]

In [155]:
df['Name'].value_counts()

Name
Rotom         6
Castform      4
Deoxys        4
Darmanitan    4
Pumpkaboo     4
             ..
Zarude        1
Regieleki     1
Regidrago     1
Glastrier     1
Spectrier     1
Name: count, Length: 898, dtype: int64

In [156]:
df[df['base_experience']>500]

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
294,294,Blissey,,Normal,540,255,10,10,75,135,...,46.8 kg (103.2 lbs),1. Natural Cure2. Serene GraceHealer (hidden a...,3 HP,"30 (3.9% with PokéBall, full HP)",140 (higher than normal),608,Fast,Fairy,"0% male, 100% female","40 (10,024–10,280 steps)"

In [157]:
df.loc[df['Name'].idxmax()]

Unnamed: 0                                      839
Name                                        Zygarde
Evolution                                 50% Forme
Type                                  Dragon Ground
Total                                           600
HP                                              108
Attack                                          100
Defense                                         121
Sp.Atk                                           81
Sp.Def                                           95
Speed                                            95
Species                               Order Pokémon
Height                               5.0 m (16′05″)
Weight                         305.0 kg (672.4 lbs)
abilities           1. Aura Break2. Power Construct
ev_yield                                       3 HP
catch_rate          3 (0.4% with PokéBall, full HP)
base_friendship               0 (lower than normal)
base_experience                                 270
growth_rate                                    Slow
eggs_groups                            Undiscovered
gender_rate                              Genderless
eggs_cycles_rate          120 (30,584–30,840 steps)
Name: 839, dtype: object

In [158]:
df.sort_values(by='Total', ascending= False).head()

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,950.0 kg (2094.4 lbs),1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
194,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,122.0 kg (269.0 lbs),1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
464,464,Rayquaza,Mega Rayquaza,Dragon Flying,780,105,180,100,180,100,...,206.5 kg (455.3 lbs),1. Air Lock,"2 Attack, 1 Special Attack","45 (5.9% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
195,195,Mewtwo,Mega Mewtwo Y,Psychic,780,106,150,70,194,120,...,122.0 kg (269.0 lbs),1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
460,460,Kyogre,Primal Kyogre,Water,770,100,150,90,180,160,...,352.0 kg (776.0 lbs),1. Drizzle,3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),302,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"

In [159]:
df['Total'].mean()

np.float64(439.31483253588516)

In [160]:
df[(df['Type'] == 'Psychic') & (df['Total'] >= 100)]

Empty DataFrame
Columns: [Unnamed: 0, Name, Evolution, Type, Total, HP, Attack, Defense, Sp.Atk, Sp.Def, Speed, Species, Height, Weight, abilities, ev_yield, catch_rate, base_friendship, base_experience, growth_rate, eggs_groups, gender_rate, eggs_cycles_rate]
Index: []

[0 rows x 23 columns]

In [161]:
df.sort_values(by='Total', ascending= False).head()

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,Weight,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate
1033,1033,Eternatus,Eternamax,Poison Dragon,1125,255,115,250,125,250,...,950.0 kg (2094.4 lbs),1. Pressure,3 HP,"255 (33.3% with PokéBall, full HP)",0 (lower than normal),345,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
194,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,122.0 kg (269.0 lbs),1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
464,464,Rayquaza,Mega Rayquaza,Dragon Flying,780,105,180,100,180,100,...,206.5 kg (455.3 lbs),1. Air Lock,"2 Attack, 1 Special Attack","45 (5.9% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
195,195,Mewtwo,Mega Mewtwo Y,Psychic,780,106,150,70,194,120,...,122.0 kg (269.0 lbs),1. PressureUnnerve (hidden ability),3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"
460,460,Kyogre,Primal Kyogre,Water,770,100,150,90,180,160,...,352.0 kg (776.0 lbs),1. Drizzle,3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),302,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)"

In [162]:
df.loc[df['Total'].idxmax()]

Unnamed: 0                                        1033
Name                                         Eternatus
Evolution                                    Eternamax
Type                                     Poison Dragon
Total                                             1125
HP                                                 255
Attack                                             115
Defense                                            250
Sp.Atk                                             125
Sp.Def                                             250
Speed                                              130
Species                               Gigantic Pokémon
Height                                 20.0 m (65′07″)
Weight                           950.0 kg (2094.4 lbs)
abilities                                  1. Pressure
ev_yield                                          3 HP
catch_rate          255 (33.3% with PokéBall, full HP)
base_friendship                  0 (lower than normal)
base_experience                                    345
growth_rate                                       Slow
eggs_groups                               Undiscovered
gender_rate                                 Genderless
eggs_cycles_rate             120 (30,584–30,840 steps)
Name: 1033, dtype: object

In [163]:
df.groupby('Type')['HP'].mean()

Type
Bug              51.263158
Bug Electric     63.500000
Bug Fairy        50.000000
Bug Fighting     84.500000
Bug Fire         70.000000
                   ...
Water Ice        90.000000
Water Poison     61.666667
Water Psychic    83.833333
Water Rock       76.600000
Water Steel      84.000000
Name: HP, Length: 192, dtype: float64

In [164]:
df.groupby('Type')['Sp.Atk'].mean().idxmax

<bound method Series.idxmax of Type
Bug               39.368421
Bug Electric      88.500000
Bug Fairy         75.000000
Bug Fighting      67.500000
Bug Fire          92.500000
                    ...
Water Ice         80.000000
Water Poison      61.666667
Water Psychic     90.000000
Water Rock        58.800000
Water Steel      111.000000
Name: Sp.Atk, Length: 192, dtype: float64>

In [165]:
df.columns.to_list()

['Unnamed: 0',
 'Name',
 'Evolution',
 'Type',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp.Atk',
 'Sp.Def',
 'Speed',
 'Species',
 'Height',
 'Weight',
 'abilities',
 'ev_yield',
 'catch_rate',
 'base_friendship',
 'base_experience',
 'growth_rate',
 'eggs_groups',
 'gender_rate',
 'eggs_cycles_rate']

In [166]:
df['Power'] = df['Attack'] + df['Sp.Atk']

In [167]:
df.loc[df['Speed'].idxmin()]

Unnamed: 0                                                    262
Name                                                      Shuckle
Evolution
Type                                                     Bug Rock
Total                                                         505
HP                                                             20
Attack                                                         10
Defense                                                       230
Sp.Atk                                                         10
Sp.Def                                                        230
Speed                                                           5
Species                                              Mold Pokémon
Height                                              0.6 m (2′00″)
Weight                                         20.5 kg (45.2 lbs)
abilities           1. Sturdy2. GluttonyContrary (hidden ability)
ev_yield                             1 Defense, 1 Special Defense
catch_rate                     190 (24.8% with PokéBall, full HP)
base_friendship                                       50 (normal)
base_experience                                               177
growth_rate                                           Medium Slow
eggs_groups                                                   Bug
gender_rate                                  50% male, 50% female
eggs_cycles_rate                           20 (4,884–5,140 steps)
Power                                                          20
Name: 262, dtype: object

In [168]:
df[abs(df['Attack']-df['Defense']) < 10].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1. OvergrowChlorophyll (hidden ability),1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",114
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,1. OvergrowChlorophyll (hidden ability),"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",142

In [169]:
df.sort_values(by='Speed', ascending= False).head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
1038,1038,Regieleki,,Electric,580,80,100,50,100,50,...,1. Transistor,3 Speed,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",200
469,469,Deoxys,Speed Forme,Psychic,600,50,95,90,95,90,...,1. Pressure,"1 Attack, 1 Special Attack, 1 Speed","3 (0.4% with PokéBall, full HP)",0 (lower than normal),270,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",190

In [170]:
df['Type'].value_counts().idxmax()

'Water '

In [171]:
df[(df['HP']>100) & (df['Speed']< 50)].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
52,52,Jigglypuff,,Normal Fairy,270,115,45,20,45,25,...,1. Cute Charm2. CompetitiveFriend Guard (hidde...,2 HP,"170 (22.2% with PokéBall, full HP)",50 (normal),95,Fast,Fairy,"25% male, 75% female","10 (2,314–2,570 steps)",90
53,53,Wigglytuff,,Normal Fairy,435,140,70,45,85,50,...,1. Cute Charm2. CompetitiveFrisk (hidden ability),3 HP,"50 (6.5% with PokéBall, full HP)",50 (normal),196,Fast,Fairy,"25% male, 75% female","10 (2,314–2,570 steps)",155

In [172]:
df[(df['Attack']> 500) & (df['Defense'] > 500)]

Empty DataFrame
Columns: [Unnamed: 0, Name, Evolution, Type, Total, HP, Attack, Defense, Sp.Atk, Sp.Def, Speed, Species, Height, Weight, abilities, ev_yield, catch_rate, base_friendship, base_experience, growth_rate, eggs_groups, gender_rate, eggs_cycles_rate, Power]
Index: []

[0 rows x 24 columns]

In [173]:
df[(df["Attack"]> 120)].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
7,7,Charizard,Mega Charizard X,Fire Dragon,634,78,130,111,130,85,...,1. BlazeSolar Power (hidden ability),3 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),240,Medium Slow,"Dragon, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",260
19,19,Beedrill,Mega Beedrill,Bug Poison,495,65,150,40,15,80,...,1. SwarmSniper (hidden ability),"2 Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),178,Medium Fast,Bug,"50% male, 50% female","15 (3,599–3,855 steps)",165

In [174]:
df[df['Speed']>90]['Name']

6       Charizard
7       Charizard
8       Charizard
19       Beedrill
22        Pidgeot
          ...
1036      Urshifu
1037       Zarude
1038    Regieleki
1041    Spectrier
1044      Calyrex
Name: Name, Length: 251, dtype: str

In [175]:
df[df['HP']<50].shape[0]

193

In [176]:
df[(df['Defense'] >= 50 ) & (df['Defense'] <= 100)].shape[0]

679

In [177]:
df.sort_values(by='Speed', ascending= False).head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
1038,1038,Regieleki,,Electric,580,80,100,50,100,50,...,1. Transistor,3 Speed,"3 (0.4% with PokéBall, full HP)",35 (lower than normal),290,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",200
469,469,Deoxys,Speed Forme,Psychic,600,50,95,90,95,90,...,1. Pressure,"1 Attack, 1 Special Attack, 1 Speed","3 (0.4% with PokéBall, full HP)",0 (lower than normal),270,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",190

In [178]:
df['HP'].min()

np.int64(1)

In [179]:
df.loc[df['Defense'].idxmax()]

Unnamed: 0                                        1033
Name                                         Eternatus
Evolution                                    Eternamax
Type                                     Poison Dragon
Total                                             1125
HP                                                 255
Attack                                             115
Defense                                            250
Sp.Atk                                             125
Sp.Def                                             250
Speed                                              130
Species                               Gigantic Pokémon
Height                                 20.0 m (65′07″)
Weight                           950.0 kg (2094.4 lbs)
abilities                                  1. Pressure
ev_yield                                          3 HP
catch_rate          255 (33.3% with PokéBall, full HP)
base_friendship                  0 (lower than normal)
base_experience                                    345
growth_rate                                       Slow
eggs_groups                               Undiscovered
gender_rate                                 Genderless
eggs_cycles_rate             120 (30,584–30,840 steps)
Power                                              240
Name: 1033, dtype: object

In [180]:
df['growth_rate'].unique()

<StringArray>
['Medium Slow', 'Medium Fast', 'Fast', 'Slow', 'Fluctuating', 'Erratic']
Length: 6, dtype: str

In [181]:
df['growth_rate'].value_counts()

growth_rate
Medium Fast    435
Slow           256
Medium Slow    246
Fast            68
Erratic         26
Fluctuating     14
Name: count, dtype: int64

In [182]:
df[df['Total'] > 100].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,abilities,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1. OvergrowChlorophyll (hidden ability),1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",114
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,1. OvergrowChlorophyll (hidden ability),"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",142

In [183]:
df.groupby('Type')['Speed'].mean()

Type
Bug               47.684211
Bug Electric      63.000000
Bug Fairy        104.000000
Bug Fighting      97.500000
Bug Fire          80.000000
                    ...
Water Ice         63.750000
Water Poison      85.000000
Water Psychic     52.000000
Water Rock        43.600000
Water Steel       60.000000
Name: Speed, Length: 192, dtype: float64

In [184]:
df.assign(total = df['Attack']+df['Speed']).sort_values(by='total', ascending= False).head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,total
467,467,Deoxys,Attack Forme,Psychic,600,50,180,20,180,20,...,"1 Attack, 1 Special Attack, 1 Speed","3 (0.4% with PokéBall, full HP)",0 (lower than normal),270,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",360,330
194,194,Mewtwo,Mega Mewtwo X,Psychic Fighting,780,106,190,100,154,100,...,3 Special Attack,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",344,320

In [185]:
df['Bulk'] = df['HP'] + df['Defense']

In [186]:
df[df['Bulk']> 200].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,Bulk
3,3,Venusaur,Mega Venusaur,Grass Poison,625,80,100,123,122,120,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",222,203
97,97,Golem,,Rock Ground,495,80,120,130,55,65,...,3 Defense,"45 (5.9% with PokéBall, full HP)",50 (normal),223,Medium Slow,Mineral,"50% male, 50% female","15 (3,599–3,855 steps)",175,210

In [187]:
df.sort_values(by='Height', ascending= False) .head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,Bulk
930,930,Celesteela,,Steel Flying,570,97,101,103,107,101,...,"1 Attack, 1 Defense, 1 Special Attack","45 (5.9% with PokéBall, full HP)",0 (lower than normal),257,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",208,200
255,255,Steelix,,Steel Ground,510,75,85,200,55,65,...,2 Defense,"25 (3.3% with PokéBall, full HP)",50 (normal),179,Medium Fast,Mineral,"50% male, 50% female","25 (6,169–6,425 steps)",140,275

In [188]:
df[df['Attack']== df['Defense']].shape[0]

105

In [189]:
df[df['Sp.Atk'] > df['Attack']].shape[0]

362

In [190]:
df[df['Speed']<50].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,Bulk
0,0,Bulbasaur,,Grass Poison,318,45,49,49,65,65,...,1 Special Attack,"45 (5.9% with PokéBall, full HP)",50 (normal),64,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",114,94
9,9,Squirtle,,Water,314,44,48,65,50,64,...,1 Defense,"45 (5.9% with PokéBall, full HP)",50 (normal),63,Medium Slow,"Monster, Water 1","87.5% male, 12.5% female","20 (4,884–5,140 steps)",98,109

In [191]:
threshold = df['HP'].quantile(0.9)
df[df['HP']> threshold].shape[0]

87

In [192]:
df[(df['Speed']>50)&(df['HP']>50)&(df['Attack']>50)].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,Bulk
1,1,Ivysaur,,Grass Poison,405,60,62,63,80,80,...,"1 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),142,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",142,123
2,2,Venusaur,,Grass Poison,525,80,82,83,100,100,...,"2 Special Attack, 1 Special Defense","45 (5.9% with PokéBall, full HP)",50 (normal),236,Medium Slow,"Grass, Monster","87.5% male, 12.5% female","20 (4,884–5,140 steps)",182,163

In [193]:
df[(df['HP']>120) & (df['Speed']>80)].head(2)

,Unnamed: 0,Name,Evolution,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,...,ev_yield,catch_rate,base_friendship,base_experience,growth_rate,eggs_groups,gender_rate,eggs_cycles_rate,Power,Bulk
348,348,Slaking,,Normal,670,150,160,100,95,65,...,3 HP,"45 (5.9% with PokéBall, full HP)",50 (normal),252,Slow,Field,"50% male, 50% female","15 (3,599–3,855 steps)",255,250
582,582,Giratina,Altered Forme,Ghost Dragon,680,150,100,120,100,120,...,3 HP,"3 (0.4% with PokéBall, full HP)",0 (lower than normal),306,Slow,Undiscovered,Genderless,"120 (30,584–30,840 steps)",200,270

In [194]:
df[['Name','Total']].head(15)

          Name  Total
0    Bulbasaur    318
1      Ivysaur    405
2     Venusaur    525
3     Venusaur    625
4   Charmander    309
5   Charmeleon    405
6    Charizard    534
7    Charizard    634
8    Charizard    634
9     Squirtle    314
10   Wartortle    405
11   Blastoise    530
12   Blastoise    630
13    Caterpie    195
14     Metapod    205

In [195]:
df[df['Attack']<60].count()

Unnamed: 0          277
Name                277
Evolution           277
Type                277
Total               277
HP                  277
Attack              277
Defense             277
Sp.Atk              277
Sp.Def              277
Speed               277
Species             277
Height              277
Weight              277
abilities           277
ev_yield            277
catch_rate          277
base_friendship     277
base_experience     277
growth_rate         277
eggs_groups         277
gender_rate         277
eggs_cycles_rate    277
Power               277
Bulk                277
dtype: int64

In [198]:
# df['Height'].dtype
# df['Height'] = pd.to_numeric(df['Height'], errors='coerce')
df['Height']= df['Height'].str.extract(r'(\d+\.?\d*)').astype(float)

In [199]:
df['Height'].head()

0    0.7
1    1.0
2    2.0
3    2.0
4    0.6
Name: Height, dtype: float64

In [ ]:
df.head(5)